server:
  port: 8014
  web:
    flux:
      enabled: true

# 定时任务配置
monitor:
  task:
    cron: "0 0 0/4 * * ?"  # 每4小时执行一次，可按需修改

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6033/building_energy_standard?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456



  # 定时任务线程池
  task:
    scheduling:
      pool:
        size: 2                    # 定时任务线程数（支持多个定时任务并行）
      thread-name-prefix: scheduled-task-
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false  # 禁用时间戳，使用字符串格式
  main:
    allow-bean-definition-overriding: true



  dashscope:
    api-key: ${OPENAI_API_KEY}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen-plus
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            schema: classpath:db/schema-mysql.sql
            platform: mysql
    mcp:
      server:
        name: my-spring-server
        type: async
        version: 1.0.0
        request-timeout: 120s
        enabled: true
        sse:
          enabled: true
        streamable-http:
          enabled: true
  data:
    redis:
      redis:
        lettuce:
          pool:
            max-active: 32
            max-idle: 16
            min-idle: 8
      port: 6379
      host: localhost
      password: infini_rag_flow
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: "mcp:"
      use-key-prefix: true
      time-to-live: 1200000


pdf:
  storage:
    path: ./pdf-files           # PDF 文件存放的本地目录
weather:
  qweather:
    key: ${QWEATHER_API_KEY}
    base-url: https://mc3aaqqcc7.re.qweatherapi.com

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.McpServices: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.example.Entity


baidu:
  search:
    api-key: ${BAI_DU_API_KEY}  # 百度千帆 API Key
    secret-key: ${BAI_DU_SECRET_KEY}
    base-url: https://qianfan.baidubce.com/v2/ai_search/web_search
  map:
    api-key: ${BAIDU_MAP_API_KEY}

alibaba:
  cloud:
    access-key-id: ${accessKey}
    access-key-secret: ${secretKey}
    bailian:
      workspace-id: ${workspaceId}
      default-index-id: ${indexId}  # 默认知识库ID
      endpoint: bailian.cn-beijing.aliyuncs.com

report:
  output:
    dir:
      path: ./report


