server:
  tomcat:
    threads:
      max: 300        # 默认 200，SSE 长连接多需要更多
    accept-count: 100  # 等待队列
  port: 9090


spring:
  ai:
    dashscope:
        api-key: ${OPENAI_API_KEY}
        options:
          model: qwen-plus
  chat:
    memory:
      repository:
        jdbc:
          initialize-schema: always
          schema: classpath:db/schema-mysql.sql
          platform: mysql

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      task:
        scheduling:
          pool:
            size: 4
    url: jdbc:mysql://localhost:3306/building_energy_standard?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update          # 第一次运行自动建表，生产环境建议用 validate 或手动管理
    show-sql: true              # 打印 SQL 日志，便于调试
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      redis:
        lettuce:
          pool:
            max-active: 32
            max-idle: 16
            min-idle: 8
      port: 6379
      host: localhost
      password: infini_rag_flow
weather:
  qweather:
    key: ${QWEATHER_API_KEY}
    base-url: https://mc3aaqqcc7.re.qweatherapi.com

pdf:
  storage:
    path: ./pdf-files           # PDF 文件存放的本地目录

alibaba:
  cloud:
    access-key-id: ${accessKey}
    access-key-secret: ${secretKey}
    bailian:
      workspace-id: ${workspaceId}
      default-index-id: ${indexId}  # 默认知识库ID
      endpoint: bailian.cn-beijing.aliyuncs.com

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.springframework.ai.chat.client: DEBUG
    org.springframework.ai.chat.model: DEBUG
    org.springframework.ai.tool: DEBUG